stages:
  - test

setup-test-hvault:
  stage: test
  script:
    - echo "Testing connection to HashiCorp Vault..."
    # Définir l'adresse de Vault
    - export VAULT_ADDR="https://vault.staging.echonen.com:8200"
    - export VAULT_NAMESPACE="cloud"
    
    # Authentification à Vault avec approle
    - export VAULT_TOKEN=$(vault login -method=approle role_id=$VAULT_ROLE_ID secret_id=$VAULT_SECRET_ID)
    
    # Vérifier le statut de Vault
    - vault status
    
    # Récupérer des secrets depuis Vault avec API (curl)
    - echo "Fetching secrets from Vault via API..."
    - export REDIS_USER=$(curl --header "X-Vault-Token: $VAULT_TOKEN" --request GET $VAULT_ADDR/v1/secret/data/redis/RDO021000358 | jq -r '.data.data.user')
    - export REDIS_PASSWORD=$(curl --header "X-Vault-Token: $VAULT_TOKEN" --request GET $VAULT_ADDR/v1/secret/data/redis/RDO021000358 | jq -r '.data.data.password')
    
    # Utilisation des secrets récupérés
    - echo "Redis user: $REDIS_USER"
    - echo "Redis password: $REDIS_PASSWORD"
  
  secrets:
    VAULT_ROLE_ID:
      vault: "my-vault"
      path: "kv/role-id"
      field: "role_id"
    VAULT_SECRET_ID:
      vault: "my-vault"
      path: "kv/secret-id"
      field: "secret_id"

only:
  - test-hvault
